# Generated by Django 4.2.24 on 2025-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_ownermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Bus_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Source', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('Departure', models.TimeField(blank=True, null=True)),
                ('Arrival', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
