# Generated by Django 4.2.24 on 2025-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_busmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='busimage/'),
        ),
    ]
