# Generated by Django 4.2.24 on 2025-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0005_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
