# Generated by Django 4.2.24 on 2025-11-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0007_feedbackmodel_complaintmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_capacity', models.IntegerField(blank=True, null=True)),
                ('Source', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.loginmodel')),
                ('OWNERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.ownermodel')),
            ],
        ),
    ]
