# Generated by Django 4.2.24 on 2025-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0008_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='cabimage/'),
        ),
    ]
