# Generated by Django 4.2.24 on 2025-11-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0009_vehiclemodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.usermodel')),
                ('VEHICLEID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.vehiclemodel')),
            ],
        ),
    ]
